"|
"| File    : ~/.vim/vimrc
"| Author  : Fabien Cazenave
"| Source  : https://github.com/fabi1cazenave/dotFiles
"| Licence : WTFPL
"|

" set gdefault                      " regexp: s/foo/bar/g by default
set formatoptions=croqlj            " 'j' kills ponies
set nojoinspaces                    " let 'J' be 'gJ'

let $VIMHOME = glob('~/.vim')   	" main Vim configuration directory
"let $VIMHOME = expand('%:p:h')  	" directory of current vimrc file (~/.vim)
"let s:VimHome = expand('%:p:h') 	" directory of current vimrc file (~/.vim)
"let s:VimTemp = s:VimHome.'/tmp'	" one directory to rule all Vim temp files
let s:VimTemp = $VIMHOME.'/tmp' 	" one directory to rule all Vim temp files

" two solutions to let CTRL-ZXCV behave like in Notepad:
"  • the standard "mswin.vim" resource: source $VIMRUNTIME/mswin.vim
"  • the "cua-mode.vim" plugin: https://github.com/fabi1cazenave/cua-mode.vim
" (the CUA mode, by default, preserves other Vim shortcuts much better)

" modern behavior
"set nocompatible                	" required for a multi-level undo/redo stack
set mouse=a                     	" enable mouse selection
"set clipboard=unnamedplus       	" use the common clipboard as default register

augroup linterConfiguration
  " autocmd FileType xml  setlocal  makeprg=xmllint\ -
  " autocmd FileType xml  setlocal equalprg=xmllint\ --format\ -
  " autocmd FileType html setlocal equalprg=xmllint\ --html\ --format\ -
  " autocmd FileType html setlocal equalprg=tidy\ -q\ -i\ -w\ 80\ -utf8\ --quote-nbsp\ no\ --output-xhtml\ yes\ --show-warnings\ no\ --show-body-only\ auto\ --tidy-mark\ no\ -
  " autocmd FileType json setlocal equalprg=python\ -mjson.tool
  " unfortunately, `formatprg' is a global option
  " autocmd FileType xml  setlocal formatprg=xmllint\ --format\ -
  " autocmd FileType html setlocal formatprg=xmllint\ --html\ --format\ -
  " autocmd FileType json setlocal formatprg=python\ -mjson.tool
augroup END

augroup zip
  autocmd BufReadCmd *.jar,*.xpi call zip#Browse(expand("<amatch>"))
augroup END

augroup javascript
  autocmd BufNewFile,BufReadPost *.webapp set filetype=json
  autocmd BufNewFile,BufReadPost *.jsm    set filetype=javascript
  " autocmd BufReadPost *.js set fdl=1
  " autocmd FileType javascript set fdl=1
augroup END

"|    Auto-reload configuration files                                       {{{
"|=============================================================================

" source configuration files
" on save to apply all changes immediately

augroup configurationFiles
  autocmd BufWritePost vimrc         source %
  autocmd BufWritePost .vimrc        source %
  autocmd BufWritePost _vimrc        source %
  autocmd BufWritePost Xresources    !xrdb -load ~/.Xresources
  autocmd BufWritePost .Xresources   !xrdb -load ~/.Xresources
  autocmd BufWritePost tmux.conf     !tmux source-file ~/.tmux.conf
  autocmd BufWritePost .tmux.conf    !tmux source-file ~/.tmux.conf
  autocmd BufWritePost gtkrc         !gtkrc-reload
  autocmd BufWritePost gtkrc-2.0     !gtkrc-reload
  autocmd BufWritePost .gtkrc-2.0    !gtkrc-reload
augroup END

" autocmd! BufNewFile,BufRead * 0r ~/.vim-include
iabbrev gebi getElementById
iabbrev _date <C-r>=strftime('%d/%m/%Y')<CR>

" everytime we change window, check if file has been updated outside of the editor
autocmd WinEnter * checktime

"http://vim.wikia.com/wiki/Fix_syntax_highlighting
"autocmd BufEnter * :syntax sync fromstart
"}}}

"|    Plugins                                                               {{{
"|=============================================================================

filetype off       " required!
if filereadable($VIMHOME.'/plugins.vim')
  source $VIMHOME/plugins.vim
endif
filetype plugin indent on

" CUA-mode.vim: adjusting the balance between Vim and standard shortcuts
behave xterm                    	" possible values: xterm, mswin
let g:cua_mode   = 1            	" standard Vim shortcuts + CTRL-ZXCV
let g:cua_arrows = 3            	" Notepad-mode for arrows/backspace/delete
if has('gui_running')           	" right-click shows a popup menu in GUI mode
  set mousemodel=popup_setpos
endif
" set selectmode=

" if exists("Ranger")
noremap <silent> <Esc>e :call Ranger()<CR>
" endif

"}}}

"|    Mappings                                                              {{{
"|=============================================================================

" disable digraph input to make <^> work faster
set nodigraph
set encoding=utf-8

" make Y copy to the end of the line (more consistant with D, C, etc.)
map Y y$

" the Ex mode is useless (except for Vi compatibility), disable it
" map Q <Nop>
" Alternative: use q: instead
nmap Q q:

" U is useless (except for Vi compatibility), make it a redo instead
map U <C-r>

" make K more consistent with J (J = join, K = split)
nnoremap K i<CR><Esc>k$
" Alternative: use a real 'Man' on K
" runtime ftplugin/man.vim
" nnoremap K :Man <C-r><C-w><CR>

" use :W to sudo-write the current buffer
command! W w !sudo tee "%" > /dev/null
" command! W w !sudo dd of=%

" Enter as leader key
" let mapleader = "\<Enter>"
" Alternative: Space as leader key
" nmap <Space> <Nop>
" let mapleader = "\<Space>"
" Alternative: Space/BackSpace for Page Down/Up
noremap <BS> <PageUp>
noremap <Space> <PageDown>

" g<Enter> to follow tags (e.g. help links)
noremap g<CR> g<C-]>
noremap <C-]> g<C-]>

" other specific mappings
if filereadable($VIMHOME.'/mappings.vim')
  source $VIMHOME/mappings.vim
endif
"}}}

"|    Terminal                                                              {{{
"|=============================================================================

set shell=/usr/bin/zsh
set t_Co=256          	" because all terms should support 256 colors nowadays…
set notitle           	" don’t set the title to “Thanks for flying vim” on exit
set guipty            	" better (?) terminal emulation in GUI mode

" handle screen / tmux
if &term =~ '^screen'
  " proper italics (≠ standout)
  set t_so=[7m      	" warning: ^[ must be entered as <C-v><C-[>
  set t_ZH=[3m
  " send the current filename to screen / tmux
  " exe "set title titlestring=Vim:%f"
  " exe "set title t_ts=\<ESC>k t_fs=\<ESC>\\"
endif
"}}}

"|    User Interface                                                        {{{
"|=============================================================================
"set visualbell

set hidden            	" don’t ask before closing a window

set showmode          	" display current mode blow the status line
set showtabline=2     	" show tabbar even for a single buffer
set laststatus=2      	" always show the status line
set ruler             	" display line/col position in the status line
set cursorline        	" highlight current line
set splitbelow        	" consistency with most tiling WMs (wmii, i3…)
set splitright        	" consistency with most tiling WMs (wmii, i3…)
set virtualedit=block 	" easier rectangular selections

" line numbers
set number            	" show absolute line numbers (:set nu)
"set relativenumber    	" show relative line numbers (:set rnu)
set scrolloff=5       	" number of screen lines to show around the cursor
set numberwidth=6     	" minimal number width (not working?)

" show tabs / nbsp / trailing spaces
set list listchars=nbsp:·,tab:¬·,trail:¤,extends:▶,precedes:◀

" minimal interface when running in GUI mode
set guioptions=
set guifont=Inconsolata\ 11

" syntax highlighting
syntax enable
set synmaxcol=200     	" don’t try to highlight super long lines
colorscheme kalahari  	" https://github.com/fabi1cazenave/kalahari.vim

" This works but always selects the last tab when Vim is resized:
" autocmd VimResized * tabdo wincmd =
function! AutoResizeWindows()
  let tabnr = tabpagenr()
  tabdo wincmd =
  exe "tabnext " . tabnr
endfunction
augroup resizeGroup
  autocmd VimResized * call AutoResizeWindows()
augroup END

"}}}

"|    General settings                                                      {{{
"|=============================================================================

set encoding=utf-8

" this should be the default but some distros disable modelines by default…
set modeline
set modelines=5

" use the current file’s directory as Vim’s working directory
" Alternative: 'airblaide/vim-rooter'
" set autochdir         	" XXX not working on MacOSX

set showmatch         	" when inserting a bracket, briefly jump to its match
"set filetype=vim      	" trigger the FileType event when set (local to buffer)

" 80-character lines (= Mozilla guidelines)
set textwidth=80      	" line length above which to break a line
set colorcolumn=+0    	" highlight the textwidth limit
set nowrap
"set nowrapscan
set linebreak

" two-space indentation except for Python and makefiles
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
" set cindent
set smartindent
set shiftround
"set autoindent
"set foldmethod=indent
augroup indents
  autocmd FileType ?akefile set noexpandtab
  autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab
  autocmd FileType html,xhtml,javascript,css,c,cpp,python setlocal foldmethod=indent
augroup END

" search settings
set hlsearch        	" highlight search results
set incsearch       	" incremental search: find as you type
set ignorecase      	" search is case-insensitive…
" set smartcase       	" … except if the search pattern contains uppercase chars
set nowrapscan      	" don’t loop through search results
highlight incsearch cterm=underline " in Shanti we trust

" http://stackoverflow.com/questions/1551231/highlight-variable-under-cursor-in-vim-like-in-netbeans
" autocmd CursorMoved * exe printf('match IncSearch /\V\<%s\>/', escape(expand('<cword>'), '/\'))
" autocmd CursorMoved * exe printf('match ColorColumn /\V\<%s\>/', escape(expand('<cword>'), '/\'))

" case-insensitive tab completion in the command line
set wildmenu          " enhanced command-line completion in the status line
set wildmode=longest,full " (use `list:longest` to complete files like a shell)
if exists("&wildignorecase")
  set wildignorecase
endif
set showfulltag

" disable incrementation of octal numbers
set nrformats=hex

" set matchpairs+=<:>
"}}}

let @h="this is a test."
let @g="ggVGd"

" vim: set ft=vim fdm=marker fmr={{{,}}} fdl=0:
